### ISSUE TITLE
Frage zum Thema SASS compiling

### ISSUE THREAD

**Issue by FNGR2911** [reactbuch/vote-example#1]
Danke erst einmal für dieses tolle Buch! Ich bin zwar erst bei Teil II, aber bisher scheint es ein absolut super Buch zu sein, um endlich in das Thema React einzusteigen. Bevor ich jetzt aber mit der VoteApp anfange, drängt sich mir als Frontend-Designer eine Frage auf:

Wie gehe ich in einer React-SPA am Besten mit dem Thema SASS compiling/CSS um? Ich weiß, dass man per Webpack auch irgendwie SASS direkt importieren kann, ähnlich wie ein JS-Modul, das man importiert. 

Allerdings möchte ich es gerne "sauber" getrennt halten, wie bei einer klassischen WebApp. Bisher habe ich als Task-Runner immer mit Gulp gearbeitet. 

Sollte ich Gulp neben Webpack laufen lassen um das SCSS zu kompilieren? Sollte ich auf eine reine Webpack-Lösung setzen? Oder per Gulp irgendwie Webpack anstoßen?

Irgendwie finde ich tausend Wege im Netz, aber ich frage mich einfach, was wohl der beste Weg ist?

Für Hinweise wäre ich dankbar!

P.S.: Habe ein paar "Tippfehler" gefunden, soll ich die einfach per Mail zukommen lassen? ;)

**Comment by nilshartmann** [comment]
Hallo,

schön, dass Dir das Buch bislang gefällt! ☺️

Wenn ich deine Frage richtig verstehe, möchtest Du als Ausgabe deines Buildprozess weiterhin eine "reguläre" CSS-Datei erhalten, die Du in deiner HTML-Seite einbinden kannst?

Es gibt mehrere Möglichkeiten, wie Du dieses Problem lösen kannst - ich denke, alle von dir skizzierten Wege würden grundsätzlich funktionieren.

Ich würde versuchen, so lange es geht, bei nur einem Tool zu bleiben. Und da Webpack quasi gesetzt ist, wäre das also Webpack. 

Um zunächst Webpack mit SASS in CSS zu compilieren, benötigst Du den SASS-Loader (https://github.com/jtangelder/sass-loader) für Webpack. In einer Stelle deiner Anwendung musst Du dann mittels `require` oder `import` dein "Root" SASS-File einbinden (z.B. in `main.js`). Über diese Referenz findet Webpack dann deine Styles und compiliert sie entsprechend (funktioniert also genauso wie bei JS(X)-Dateien).

Die compilierten Styles werden dann ebenfalls mit in die zentrale Ausgabedatei aufgenommen (`dist/vote-app.js`). Durch den von Webpack generierten Code werden sie dann zur Laufzeit in den DOM eingebaut.

Wenn Du das compilierte Ergebnis in Form einer eigenständigen CSS-Datei haben möchtest, kannst Du das  extract-text Plug-in (https://github.com/webpack/extract-text-webpack-plugin) von Webpack verwenden. Mit diesem Plug-in kannst Du Artefakte, die Webpack normalerweise mit in die zentrale JavaScript-Datei aufnehmen würde, in eigene Dateien auslagern - in deinem Fall also der CSS-Code. Dann bekommst Du als Build-Ergebnis neben der JavaScript- auch eine eigene CSS-Datei, die Du in deiner `index.html`-Datei einbinden musst. (Auch in diesem Fall müsstest Du die Root-Sass-Datei irgendwo in deiner Anwendung einmal referenzieren, damit Webpack sie findet. Evtl. könnte man dafür auch einen zweiten `entry` in Webpack definieren, dass habe ich aber noch nie gemacht - weiß nicht, ob das geht).

Ich habe für dieses Setup ein ganz einfaches Beispiel gebaut, das Du in diesem Repository findest: https://github.com/nilshartmann/react-and-sass. Auf dem `master`-Branch findest Du den Ansatz ohne extract-text-plugin und auf dem Branch `extract_text_plugin` die Erweiterungen für den Einsatz von Webpack mit dem Plug-in.

Hilft dir das weiter?

Viele Grüße,
Nils

PS: Rechtschreibfehler werden genommen :-)

**Comment by FNGR2911** [comment]
Vielen vielen Dank Nils! Das hilft mir sehr weiter. Ich wußte nämlich nicht, dass es diese extract-Möglichkeit gibt, denn genau das habe ich gesucht. Danke auch für das Beispiel-Repo, damit kann ich super arbeiten!

Noch einmal Danke und die Korrekturen lassen ich mal an die gewünschte Mail-Adresse kommen :)

Viel Erfolg mit dem Buch noch!
