### ISSUE TITLE
start script in Anhang_Build-Prozess/00_Ausgangszustand

### ISSUE THREAD

**Issue by remkoo** [reactbuch/vote-example#11]
im Projekt vote-example/steps/Anhang_Build-Prozess/00_Ausgangszustand ist im package.json start Script ein falscher Pfad ("start": "node server/index.js"). Das index.js File liegt jedoch unter src/server/index.js.

**Comment by nilshartmann** [comment]
Vielen Dank für den Hinweis! Habe ich korrigiert!
