### ISSUE TITLE
Formular wird nicht geleert

### ISSUE THREAD

**Issue by Tardigra** [reactbuch/vote-example#12]
Nach Erstellung einer neuen Vote wird das Formular nicht geleert. 
Der Grund liegt in der `close()` Methode der `VoteComposer` Komponente.
Hier fehlt die entsprechende state-Referenzierung:
```
close() {
    const { onDeactivate } = this.props;
    this.setState({vote: emptyVote()});
    onDeactivate();
  }
```
anstatt:
```
...
this.setState(emptyVote());
```

**Comment by nilshartmann** [comment]
Danke für den Hinweis. Ich habe den Code entsprechend korrigiert!
