### ISSUE TITLE
npm install funktioniert nicht

### ISSUE THREAD

**Issue by andreaslauten** [reactbuch/vote-example#13]
Wenn ich versuche in dem Ordner "app" den Befehl "npm install" auszuführen, erhalte ich folgende Fehlermeldung:

`npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> phantomjs@1.9.20 install /home/andreas/vote-example/app/node_modules/phantomjs
> node install.js

sh: 1: node: not found
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andreas/vote-example/app/npm-debug.log
`
ich habe folgende Versionen von npm und nodejs installiert:
node v4.2.6
npm  v3.5.2

**Comment by nilshartmann** [comment]
Leider kann ich das Problem nicht reproduzieren - bei mir funktioniert es mit der angegebenen Node und npm Version.

Welches Betriebssystem verwendest Du? Vielleicht ist es ein OS-spezifisches Problem mit PhantomJS.

Als "Workaround" könntest Du vorübergehend auch `karma-phantomjs-launcher` und `phantomjs` aus der package.json-Datei entfernen. Dann kannst Du zwar die phantomjs-Tests nicht ausführen, aber der Rest sollte funktionieren.

**Comment by andreaslauten** [comment]
Hatte es vorher mit Linux Mint 18.2 versucht.
Mit Ubuntu 17.1 klappt es aber nun auch bei mir.
