### ISSUE TITLE
Fehler im Code: mainComponent-Property im Layout-Component (S. 171)

### ISSUE THREAD

**Issue by alinnert** [reactbuch/vote-example#2]
Hallo,

ich habe im Buch in einem Beispielcode einen Fehler entdeckt.

(Seite 171, Abschnitt 9.1 "Hands-on: Serveranbindung", Schritt 2: Votes vom Server abfragen)

Der Code beschreibt die `main.js` nachdem die nicht mehr benötigten Dummy-Daten entfernt wurden. Darunter folgenden Code:

``` jsx
ReactDOM.render(
    <Layout mainComponent={mainComponent}/>,
    document.getElementById('voteAppMountPoint')
);
```

zu diesem Zeitpunkt wird die `mainComponent` noch als Kindelement von `<Layout/>` übergeben. (da ich noch am Lesen bin, kann ich nicht sagen, ob das noch geändert wird.)

Direkt darunter wird erwähnt, dass der aktuelle Stand nach dieser Änderung im Verzeichnis `09_Server_Kommunikation/02_receive_votes` zu finden ist. Auch dort wird das über `children` gelöst.

Also in der `main.js`: `<Layout>{mainComponent}</Layout>`

Und in der `Layout.js` an der entsprechenden Stelle: `... {children} ...`

Das Beispiel im Buch dürfte so also nicht funktionieren, da `Layout` keine `mainComponent`-Property hat.

Richtig ist also:

``` jsx
ReactDOM.render(
    <Layout>{mainComponent}</Layout>,
    document.getElementById('voteAppMountPoint')
);
```

**Comment by nilshartmann** [comment]
Hi!

Vielen Dank für deine Rückmeldung! Du hast völlig recht - der Code-Abschnitt im Buch ist leider falsch und beruht auf einer früheren Version der `Layout`-Komponente, die es gar nicht ins Buch geschafft hat.

Wir werden demnächst eine Errata-Seite einrichten und dort darauf hinweisen.

Viele Grüße und noch viel Spaß beim Lesen!
Nils
