### ISSUE TITLE
Frage zu den React key-Attribut Seite 64

### ISSUE THREAD

**Issue by opensource21** [reactbuch/vote-example#5]
Auf Seite 64 gibt es den Hinweis, dass Elemente ein key Attribute haben sollten bei Listen.
- Wieso ist das nur ein Problem bei Listen? Das gilt doch für alle Elemente die Umstrukturiert werden können. Z. B. wenn man Header und Danger wechselt.
- Es wird nicht ganz klar, ob es sich nur um eine Performance-Verbesserung handelt.

**Comment by nilshartmann** [comment]
Du musst das `key` Attribute für alle Elemente verwenden, die Einträge in einer generierten Liste darstellen (die z.B. mit `Array.map()` erzeugt werden). Dabei spielt es keine Rolle, ob das Element z.B. ein `li` ist. Auch wenn Du eine Liste von `p`-Elementen erzeugst, muss jedes `p`-Element einen key-Besitzen. 
Wenn Du in einer Liste kein `key`-Attribute angibst, verwendet React den Index des Elements innerhalb der Liste als Key. Das dürfte solange kein Problem darstellen, solange sich die Reihenfolge der Liste nicht ändert. In der React Dokumentation wird aber empfohlen, immer ein `key`-Attribute zu verwenden - deswegen auch die entsprechende Warnung auf der Konsole.

Strenggenommen handelt es sich bei dem `key`-Attribute darum, React die Möglichkeit zu geben, ein Element eindeutig zu identifizieren, damit React das Element beim Vergleichen zweier virtueller DOMs finden kann. Dadurch ergibt sich dann ein Performance Gewinn, weil React genau weiß, welche beiden Elemente miteinander verglichen werden müssen, weil sie "dieselben" im alten und neuen DOM sind (und nur diese beiden dann verglichen werden müssen).

Mehr zum `key`-Attribute kannst Du hier in der React-Dokumentation finden:
- https://facebook.github.io/react/docs/lists-and-keys.html#keys
- https://facebook.github.io/react/docs/reconciliation.html#recursing-on-children

**Comment by opensource21** [comment]
Ich musste gerade mühsam lernen, dass wenn ich eine Komponente nur neu erzeugt wird, wenn sich der Key ändert. Eine Komponente als Klasse definiert, z.B. Todo, welches ein Todo mit einer Id, Beschreibung und einer Prio, wird nicht aktualisiert wenn ich {this.state.todos.map((todo) => <Todo  key = {todo.id} todo = {todo} inputChangeFunc = {this.inputChange} />)} nutze. In dem Fall muss man entweder die Id bei Änderungen ändern oder key = {Date.now()} nutzen. Diese Info fehlt im Buch.[Update: Es war ein Programmierfehler, da ich im Konstruktor Instanz-Variablen benutzt habe].

**Comment by nilshartmann** [comment]
Ich verstehe deine Frage nicht ganz, deswegen habe ich mal ein kurzes Beispiel gebaut, an dem wir das vielleicht besser besprechen können: https://github.com/nilshartmann/react-list-example.

Du findest darin eine Komponente, die eine Liste mit Todos darstellt. Wenn Du auf einen der Buttons darunter klickst, wird das entsprechende Todo verändert (Priorität wird verändert). Das aktualisierte Todo wird dann auch angezeigt.

Kannst Du mir daran zeigen, wo dir etwas unklar ist? (Wenn Du ein anderes Beispiel hast, das das Problem zeigt, kannst Du mir das auch gerne zur Verfügung stellen).

**Comment by opensource21** [comment]
Danke für das Mini-Beispiel. Ich habe den Fehler gefunden: Ich habe Instanzvariablen für Rendern benutzt. Diese wurden nur im Konstruktor gesetzt. War das erste mal, dass ich den Fehler gemacht habe und dann in Kombination mit einer Liste. Das ändern des Keys hilft, da dann immer der Konstruktor neu aufgerufen wird. Aber dann kriegt man noch ganz andere Probleme. Das ganze steht auch gut im Buch, aber Lesen und Machen sind halt doch 2 Dinge. Evtl. würde ein Kapitel "Typische Fehler und wie man sie erkennt" helfen.

Sorry für die Mühe und Vielen Dank
