### ISSUE TITLE
vote-example\steps\07_Interaktive_Komponenten\02_add_state missing babel-polyfill

### ISSUE THREAD

**Issue by opensource21** [reactbuch/vote-example#6]
At vote-example\steps\07_Interaktive_Komponenten\02_add_state the node_modul babel-polyfill is missing. I must add it with yarn add babel-polyfill. So adding
 "babel-polyfill": "^6.16.0",
to package.json

**Comment by manueldeutsch** [comment]
Hatte ebenfalls den Fehler `Module not found: Error: Cannot resolve module 'babel-polyfill'`
Habs mit `npm install --save-dev babel-polyfill` gelöst.

**Comment by nilshartmann** [comment]
Danke für Euren Hinweis. Ich habe babel-polyfill hinzugefügt. 

@mantsch: Installation mit `npm install --save babel-polyfill` (also nicht `--save-dev`), da es sich nicht um eine Entwicklungsabhängigkeit handelt, sondern die Abhängigkeit auch zur Laufzeit benötigt wird.
