### ISSUE TITLE
Problem beim Starten des Webservers

### ISSUE THREAD

**Issue by fastmick** [reactbuch/vote-example#7]
Hallo, ich habe mir das vote-example-Repository heruntergeladen und die entsprechenden Pakete via npm installiert.

Nun zu meinem Problem: 
der Server lässt nicht starten. Als Betriebssystem verwende ich Windows 10.
Vielleicht haben Sie ja eine Idee woran es liegen könnte.

Das entsprechende Log-File habe ich angehangen. 
[npm-debug.txt](https://github.com/reactbuch/vote-example/files/563889/npm-debug.txt)

Vielen Dank für Ihre Mühe im voraus.

**Comment by reactbuch** [comment]
Hallo,

wenn ich das Logfile richtig verstehe, verwendest du eine ältere Version
von NodeJS. Kannst Du mal prüfen, dass Du mindestens Version 4.5 von Node
verwendest?

Viele Grüße,
Nils

**Comment by fastmick** [comment]
Hi, zunächst einmal vielen Dank für die schnelle Hilfe :-)

Die verwendetet NodeJS-Version war tatsächlich zu alt. Nach einem Update auf die aktuelle Version (6.9.1) lässt sich der Server wie erhofft starten. Dann mal weiter mit React-JS.

Schöne Grüße
Michael
